export { default as startButton } from "./start.svg";
export { default as startKorean } from "./start_korean.svg";
export { default as pauseButton } from "./pause.svg";
export { default as pauseKorean } from "./pause_korean.svg";
export { default as stopButton } from "./stop.svg";
export { default as stopKorean } from "./stop_korean.svg";
export { default as recordButton } from "./record.svg";
export { default as recordKorean } from "./record_korean.svg";
import LeftArrow from "./leftArrow.svg?react";
import RightArrow from "./rightArrow.svg?react";
export { LeftArrow, RightArrow };
